### ISSUE TITLE
beaglebone black freertos bring up procedure??

### ISSUE THREAD

**Issue by vinayashreeks** [guileschool/BBB-rtos#1]
@guileschool    i have downloaded BBB-rtos from github repository https://github.com/guileschool/BBB-rtos
In linux pc i downloaded gcc-arm-none-eabi tool
Opened a command window and went to the path BBB-rtos-master/freertos-BBB/Demo/AM3359_BeagleBone_GCC and run make command
rtosdemo-a.bin created
I dont know what are all the files that need to be copied to to sd card to bring up freertos on BBB?????
How to write files to sd card????
can u please tell me or give me any link which has simple steps regarding this????

**Comment by guileschool** [comment]
@ vinayashreeks
Here. Youtube Tutorial
https://www.youtube.com/watch?v=RZcrx9w33D8
After watching YouTube videos, try it. If you don't succeed, try using the following methods :
Download this file( VMWARE Ubuntu Image )
http://naver.me/FV0Q3Kz5   ( Ubuntu12.04-edu.vmwarevm.7z )
Use this compressed file to work as described in YouTube videos

**Comment by guileschool** [comment]
SD CARD writer script
https://github.com/guileschool/BBB-linux/blob/master/create-sdcard.sh

**Comment by vinayashreeks** [comment]
hi 
thank you for the reply
I followed the same procedure that is shown in youtube video.
But while running ./mksdcard.sh command ,i am getting output like

> 

> ################################################################################
> 
> 		Partitioning Boot
> 
> ################################################################################
> mkfs.fat 3.0.26 (2014-03-07)
> mkfs.fat: warning - lowercase labels might not work properly with DOS or Windows
> /dev/sdb1: No such file or directory
> 
> ################################################################################
> 
> 		Partitioning rootfs
> 
> ################################################################################
> mke2fs 1.42.9 (4-Feb-2014)
> Could not stat /dev/sdb2 --- No such file or directory
> 
> The device apparently does not exist; did you specify it correctly?
> 
> ################################################################################
> 
> 		Partitioning is now done
> 		Continue to install filesystem or select 'n\' to safe exit
> 		Warning Continuing will erase files any files in the partitions
> 
> ################################################################################
> 
> Would you like to continue? [y/n] : y
> 
>  
>  
> Mount the partitions 
> mount: special device /dev/sdb1 does not exist
> mount: special device /dev/sdb2 does not exist
>  
> Emptying partitions 
>  
> 
> Syncing....
> 
> 
> now installing:  /home/BEAGLEBONE-tutorials/BBB-firmware/mkcard
> ################################################################################
> 
> 	Copying files now... will take minutes
> 
> ################################################################################
> 
> Copying boot partition
> 
> MLO copied
> 
> 
> u-boot.img copied
> rtosdemo.bin copied
> 
> uEnv.txt copied
> 
> 
> 
> Syncing...
>  
> Un-mount the partitions 
> umount2: Invalid argument
> umount: boot: not mounted
> umount2: Invalid argument
> umount: rootfs: not mounted
>  
> Remove created temp directories 
>  
> Operation Finished

After this when i inserted sd card in board, i am getting 
"CCCCCCCCCCCCCCCC "
in minicom window

can u please help me in this????
@guileschool

**Comment by vinayashreeks** [comment]
hi
Now i got success by using create-sdcard.sh file mentioned in the link above,partition got created properly and now able to bootup

THANK YOU VERY MUCH for the support @guileschool 
one single question,how to know the freertos version used in this example??
